### ISSUE TITLE
Inquietud sobre el costo del algoritmo

### ISSUE THREAD

**Issue by willtorber** [pin3da/Programming-contest#2]
Soy nuevo en este campo de la programación y realice una solución en java muy similar a este algoritmo https://github.com/pin3da/Programming-contest/blob/master/solved/Maratones%20competidas/Nacional%202014/E.cpp  y ahora debo hallar el costo del mismo.

Por el método find que usted usa, implemente el patrón de búsqueda kmp, el cual lo modifique para que retornara la posición optima  donde se debe empezar a buscar el siguiente subpatron (asi como usted lo hace).

Agradeciera mucho su ayuda en esta cuestión (determinar el costo temporal). Buen día.

**Comment by pin3da** [comment]
Hola, ¿ podría compartir su código para ayudarle más fácil ?

**Comment by willtorber** [comment]
Claro, este es: https://gist.github.com/WilliamTorres/41ce7d96efd1c53f97ba11bf3487b1f9

**Comment by pin3da** [comment]
@WilliamTorres, la solución es lineal en la sumatoria de la longitud de los patrones + el texto; Se compone de 2 partes:
- La construcción de n autómatas (que es lineal por cada patrón, lo demuestran en kmp).
- Buscar matching de los patrones en el texto, esto también es lineal. La clave está en que para cada
patrón se comienza a buscar desde donde termina el anterior, por lo tanto cada "substring" es analizado por a lo sumo 1 patrón.

Espero sirva de ayuda (:

**Comment by willtorber** [comment]
Muchas Gracias :D

**Comment by pin3da** [comment]
:+1:

**Comment by willtorber** [comment]
Que pena, entonces en si, quedaría acotado por:  Tamaño del ArrayList(resultante del split) * (n+m) ?

**Comment by pin3da** [comment]
Está acotada por ![eq](http://latex2png.com/output//latex_80eba9b81d7888ee88ae5539660518be.png)

**Comment by willtorber** [comment]
Perfecto, muchas gracias por toda la ayuda :D
